library: ~/.config/beets/musiclibrary.db

import:
    copy: no
    move: no
    write: yes
    timid: yes

match:
    strong_rec_thresh: 0.10

plugins:
    - musicbrainz

paths:
    default: $albumartist/$year - $album/$track - $title
    singleton: $artist/Singles/$title
