wallpaper {
    monitor = DP-1
    path = ~/nixos-dotfiles/assets/wallpapers/gruvbox-1.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/nixos-dotfiles/assets/wallpapers/gruvbox-1.png
    fit_mode = cover
}
